use_frameworks!

target 'SugarRecord_Example' do
  pod 'SnapKit'
  pod 'SugarRecord', :path => "../"
  pod 'SugarRecord/CoreData', :path => "../"
  pod 'SugarRecord/CoreData+iCloud', :path => "../"
end

target 'SugarRecord_Tests' do
  pod 'SugarRecord', :path => "../"
  pod 'SugarRecord/CoreData', :path => "../"
  pod 'SugarRecord/CoreData+iCloud', :path => "../"
  pod 'Quick', "~> 0.10"
  pod 'Nimble', '~> 5.0'
  pod "OHHTTPStubs"
  pod 'OHHTTPStubs/Swift'
end