use_frameworks!

target 'SugarRecord_Example' do
  pod 'SnapKit'
  pod 'SugarRecord', :path => "../"
  pod 'SugarRecord/CoreData', :path => "../"
  pod 'SugarRecord/CoreData+iCloud', :path => "../"
  pod 'SugarRecord/Realm', :path => "../"

  target 'SugarRecord_Tests' do
    inherit! :search_paths
    pod 'Quick', "~> 0.10"
    pod 'Nimble', '~> 5.0'
    pod "OHHTTPStubs"
    pod 'OHHTTPStubs/Swift'
  end
end