source 'https://github.com/CocoaPods/Specs.git'

target 'SugarRecord', :exclusive => true do
  pod "SugarRecord", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SugarRecord", :path => "../"

  
end
