highlight_color: "#19b35e;" 
highlight-dark-color: "#00a98b;"
darker-color: "#b2c6b9;" 
darker-dark-color: "#94a8a7;"
background-colour: "#e5f2ec;"
alt-link-color: "#00a98b;"
warning-color: "#b88391;"

additional_guides:
     - https://github.com/SugarRecord/SugarRecord/README.md