source 'https://rubygems.org'
gem 'json', '1.7.7'
gem 'cocoapods', :git => 'https://github.com/CocoaPods/CocoaPods.git', :branch => 'swift'
gem 'cocoapods-core', :git => 'https://github.com/CocoaPods/Core.git', :branch => 'swift'
gem 'xcodeproj',  :git => "https://github.com/CocoaPods/Xcodeproj.git"
