source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
target :tests do
  link_with 'SugarRecordTests'
  pod 'SugarRecord', :git => 'https://github.com/SugarRecord/SugarRecord.git', :tag => '1.0.3'
end
