use_frameworks!

target 'Examples' do
  pod 'SnapKit'
  pod 'SugarRecord', :path => "../"
  pod 'SugarRecord/CoreData', :path => "../"
  pod 'SugarRecord/CoreData+iCloud', :path => "../"
  pod 'SugarRecord/Realm', :path => "../"
end

target 'iOS' do
  pod 'SugarRecord', :path => "../"
  pod 'SugarRecord/CoreData', :path => "../"
  pod 'SugarRecord/CoreData+iCloud', :path => "../"
  pod 'SugarRecord/Realm', :path => "../"
  pod "Quick"
  pod "Nimble"
  pod "OHHTTPStubs"
  pod 'OHHTTPStubs/Swift'
end

target 'macOS' do
  pod 'SugarRecord', :path => "../"
  pod 'SugarRecord/CoreData', :path => "../"
  pod 'SugarRecord/CoreData+iCloud', :path => "../"
  pod 'SugarRecord/Realm', :path => "../"
end

target 'tvOS' do
  # pod 'SugarRecord', :path => "../"
  # pod 'SugarRecord/CoreData', :path => "../"
  # pod 'SugarRecord/Realm', :path => "../"
end