use_frameworks!

target 'Examples' do
  pod 'SnapKit'
  pod 'SugarRecord', :path => "../"
  pod 'SugarRecord/CoreData', :path => "../"
  pod 'SugarRecord/CoreData+iCloud', :path => "../"
  pod 'SugarRecord/Realm', :path => "../"
end

target 'Tests' do
  pod 'SugarRecord', :path => "../"
  pod 'SugarRecord/CoreData', :path => "../"
  pod 'SugarRecord/CoreData+iCloud', :path => "../"
  pod 'SugarRecord/Realm', :path => "../"
  pod 'Quick', :git => "https://github.com/quick/quick", :commit => "e72d6dc86bea6b0200a54c86820a6407cf20ebb0"
  pod 'Nimble', '~> 5.0'
  pod "OHHTTPStubs"
  pod 'OHHTTPStubs/Swift'
end