# Requires
require 'yaml'

# Fastlane Constants
fastlane_version "1.54.0"
default_platform :ios

# Constants
PODSPEC = "SugarRecord.podspec"
WORKSPACE = "SugarRecord.xcworkspace"
SCHEME_TESTS = "SugarRecordTests"

# Lanes
desc "Setup everything needed to work on the project"
lane :setup do
  carthage(command: "checkout")
end

desc "Runs the tests suite"
lane :tests do
  scan(workspace: WORKSPACE, scheme: SCHEME_TESTS, skip_build: true)
end

desc "Builds all the project targets"
lane :build do
  sh("xcodebuild -workspace '../#{WORKSPACE}' -scheme 'SugarRecord-CoreData-iOS' -configuration 'Debug' build | xcpretty")
  sh("xcodebuild -workspace '../#{WORKSPACE}' -scheme 'SugarRecord-Realm-iOS' -configuration 'Debug' build | xcpretty")
  sh("xcodebuild -workspace '../#{WORKSPACE}' -scheme 'SugarRecord-CoreData-OSX' -configuration 'Debug' build | xcpretty")
  sh("xcodebuild -workspace '../#{WORKSPACE}' -scheme 'SugarRecord-Realm-OSX' -configuration 'Debug' build | xcpretty")
  sh("xcodebuild -workspace '../#{WORKSPACE}' -scheme 'SugarRecord-CoreData-watchOS' -configuration 'Debug' build | xcpretty")
  sh("xcodebuild -workspace '../#{WORKSPACE}' -scheme 'SugarRecord-Realm-watchOS' -configuration 'Debug' build | xcpretty")
  sh("xcodebuild -workspace '../#{WORKSPACE}' -scheme 'SugarRecord-CoreData-tvOS' -configuration 'Debug' build | xcpretty")
  sh("xcodebuild -workspace '../#{WORKSPACE}' -scheme 'SugarRecord-Realm-tvOS' -configuration 'Debug' build | xcpretty")
end

lane :ci do
  setup
  build
  tests
  # version = version_bump_podspec(path: PODSPEC, bump_type: "patch")
end
